# Generated by Django 4.0 on 2023-07-03 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('con', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('post1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
