# Generated by Django 4.0 on 2023-07-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='con',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
    ]
